name: Sync Action into Veracode

on:
  workflow_dispatch:     # allow manual trigger from the Actions tab

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
    steps:
      - name: Checkout veracode
        uses: actions/checkout@v4

      - name: Clone Action
        run: |
          git clone --depth=1 https://github.com/release-0-2-0/veracode_16-jan.git /tmp/existing_veracode

      - name: Update folder with Action contents
        run: |
          # Remove old folder
          # rm -rf actions/test
          # mkdir -p actions/test

          # Copy contents from repoA
          cp -r /tmp/existing_veracode/.github/workflows/update-cli.yml .github/workflows/update-cli.yml

      - name: Commit and push changes
        run: |
          git config --list
          git config --global user.name "shailesh-veracode"
          git config --global user.email "shande@veracode.com"
          git remote set-url origin https://x-access-token:${secrets.PERSONAL_ACCESS_TOKEN}@github.com/release-0-2-0/veracode.git
          git add .github/workflows/
          git commit -m "Sync repoA main branch $(date -u '+%Y-%m-%d %H:%M:%S') [skip ci]" || echo "No changes to commit"
          git push
